export { default as About } from './about/About';
export { default as Add_Car } from './addCar/addCar';
export { default as Car } from './car/Car';
export { default as Cart } from './cart/Cart';
export { default as Checkout } from './checkout/Checkout';
export { default as CheckoutForm } from './checkout/CheckoutForm';
export { default as PaymentPage } from './checkout/PaymentPage';
export { default as Success } from './checkout/Success';
export { default as Explore } from './explore/Explore';
export { default as Home } from './home/Home';
export { default as Login } from './login/Login';
export { default as NotFound } from './notFound/NotFound';
export { default as Payment } from './payment/Payment';
export { default as Register } from './register/Register';
export { default as ServicePage } from './servicePage/ServicePage';
export { default as Contact } from './contact/Contact'